language: php

php:
  - 5.5
  - 5.6
  - '7.0'
  - hhvm

allowed_failures:
  - hhvm
  - '7.0'

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: vendor/bin/codecept run
